### ISSUE TITLE
Nethermind as rbuilder state provider

### ISSUE THREAD

**Issue by mralj** [NethermindEth/rbuilder#1]
## Goal
Nethermind client should work as a state provider for `rbuilder.` 
Firstly, the state will be provided via IPC RPC, and then we'll optimize  (e.g., Rust <> C# FFI). 

## TODOs

- [x] Implement necessary [`SatateProviderFactory` traits ](https://github.com/paradigmxyz/reth/blob/ef033abaf9105f167a778e00411e005ba9a0271e/crates/storage/storage-api/src/state.rs#L134)
- [x] Implement necessary [`StateProvider` traits](https://github.com/paradigmxyz/reth/blob/ef033abaf9105f167a778e00411e005ba9a0271e/crates/storage/storage-api/src/state.rs#L20)
- [x] Implement [`HeaderProvider` traits]()
- [x] Implement state root calculation (dependent on the Flashbots team to refactor the traits)
- [x] Test using [Backtest Builders ](https://github.com/flashbots/rbuilder?tab=readme-ov-file#backtesting)
- [x] Test using Live builder

**Here is the list of the Traits we'll have to implement:**
  
Column _Already supported by NM?_ indicates that the:
1.  RPC call already exists in the NM client
2. NM client supports both arg and return types (they are either "the same" or there is a small amount of work to be done to support the requirements fully)

If the args or return data needs to be adapted from/to NM-specific types, I propose adapters to be implemented on the `rbuilder` side where possible since this is specific to `rbuilder` and not the NM client.

### `StateProviderFactory`

|  Trait | Done? | Already supported by NM?| 
|---|---|---|
|  [latest](https://github.com/paradigmxyz/reth/blob/ef033abaf9105f167a778e00411e005ba9a0271e/crates/storage/storage-api/src/state.rs#L136) |  ✅| ✅| 
|  [history_by_block_hash](https://github.com/paradigmxyz/reth/blob/ef033abaf9105f167a778e00411e005ba9a0271e/crates/storage/storage-api/src/state.rs#L166) |  ✅ | ✅  |   
|  [last_block_number](https://github.com/paradigmxyz/reth/blob/ef033abaf9105f167a778e00411e005ba9a0271e/crates/storage/storage-api/src/block_id.rs#L20) |  ✅ | ✅  |    

### `StateProvider`

|  Trait | Done? | Already supported by NM?|
|---|---|---|
|  [storage](https://github.com/paradigmxyz/reth/blob/ef033abaf9105f167a778e00411e005ba9a0271e/crates/storage/storage-api/src/state.rs#L31) |  ✅ | ✅|   
|  [bytecode_by_hash](https://github.com/paradigmxyz/reth/blob/ef033abaf9105f167a778e00411e005ba9a0271e/crates/storage/storage-api/src/state.rs#L38) |  ✅ | ✅  | 
|  [block_hash](https://github.com/paradigmxyz/reth/blob/d5a096f52f0ffec07ccc28d231c423caf5f65184/crates/storage/storage-api/src/block_hash.rs#L10) |  ✅ | ✅  |   
|  [basic_account](https://github.com/paradigmxyz/reth/blob/d5a096f52f0ffec07ccc28d231c423caf5f65184/crates/storage/storage-api/src/account.rs#L17) |  ✅ | ✅  | 

### `HeaderProvider`
|  Trait | Done? | Already supported by NM?| 
|---|---|---|
|  [header](https://github.com/paradigmxyz/reth/blob/7250ca5d77eadafe70569ac6cb891e2682836b5b/crates/storage/storage-api/src/header.rs#L22) |   ✅ |  ✅|

**Comment by mralj** [comment]
@asdacap, can you please look into the following (by look into, I mean either let me know RPC methods if they already exist or implement new ones)

### 1. [bytecode_by_hash](https://github.com/paradigmxyz/reth/blob/ef033abaf9105f167a778e00411e005ba9a0271e/crates/storage/storage-api/src/state.rs#L38)

I'm not sure what the RPC call is for this one (or if NM supports it), here is how I implemented it (following [Ferran's PR](https://github.com/flashbots/rbuilder/pull/144)), but I don't think this is the correct implementation:

```Rust
fn bytecode_by_hash(&self, code_hash: B256) -> ProviderResult<Option<Bytecode>> {
        let address = Address::from_word(code_hash);
        let block_id = BlockId::hash(self.hash);

        let res = futures::executor::block_on(async {
            self.provider.get_code_at(address).block_id(block_id).await
        })
        .unwrap();

        Ok(Some(Bytecode::new_raw(res)))
    }
```

This doesn't look correct because the `get_code_at` RPC call expects `Address,` and the `bytecode_by_hash` trait provides `code_hash` (the hash of the code we are fetching).
So my questions are:
1. Is this code indeed incorrect? If it is incorrect,
2. Does NM already support this call out of the box, and if not,  can it be implemented on the NM side?

### 2.  calculate_state_root

We'll need an RPC call to calculate the state root (if one doesn't already exist) on the NM side. The `rbuilder` provides:
1. `parent_hash` (so we can get the previous `state_root` by reading the parent block via the provided hash) 
2. [ExecutionOutcome](https://github.com/paradigmxyz/reth/blob/d644900a8078db976cdbfb310a19df5df9b33125/crates/evm/execution-types/src/execution_outcome.rs#L37) which has [BundleState](https://github.com/bluealloy/revm/blob/7d060e18b3e926e9e7763ff44516b0f0cb941ea5/crates/database/src/states/bundle_state.rs#L401)  containing the _state diff_  (from `BundleState` struct I think we only need the `state` and the `contracts.` 

If I'm not mistaken, this should be enough to calculate _state_root_.  I
If NM doesn't already have an RPC call which supports this, can you implement one and let me know the API spec?

**Comment by asdacap** [comment]
So for 1, I think it probably mean that you'll need to get the account for the address first, which contains the codehash. 
For 2, its not available. I'll think of an API spec.

**Comment by mralj** [comment]
> So for 1, I think it probably mean that you'll need to get the account for the address first, which contains the codehash.

Yeah, but the issue is that the `bytecode_by_hash` trait doesn't have (access to) the address, it only receives the `code_hash`.
I'd have to somehow find the account by `code_hash`, is this already possible in NM via RPC? If not we'll have to add support for this as well.

**Comment by asdacap** [comment]
Ow, thats fine. I thought it only pass in Address as some kind of optimization. We can get code by hash directly.
